version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - backend
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
    networks:
      - backend

# Networks for container communication
networks:
  backend:
