"""empty message

Revision ID: 9a384a9d908d
Revises: f4d09b3091ce
Create Date: 2019-10-24 02:49:54.862775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a384a9d908d'
down_revision = 'f4d09b3091ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('contact_mail', sa.String(), nullable=True))
    op.add_column('person', sa.Column('mail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'mail')
    op.drop_column('person', 'contact_mail')
    # ### end Alembic commands ###
